ValueSet: EHDSIPersonalRelationship
Id: eHDSIPersonalRelationship
Title: "eHDSI PersonalRelationship"
Description: "The Value Set is used (optionally) to code the type of contact relationship between a person and the patient."

* ^url = "http://terminology.ehdsi.eu/ValueSet/eHDSIPersonalRelationship"
* ^experimental = false
* ^name: "EHDSIPersonalRelationship"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.3.6.1.4.1.12559.11.10.1.3.1.42.38"

* http://terminology.hl7.org/CodeSystem/v3-RoleCode#FAMMEMB "Family Member"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#FRND "unrelated friend"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#NBOR "neighbor"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#DAUFOST "foster daughter"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#AUNT "aunt"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#GRNDSON "grandson"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#GRMTH "Grandmother"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#DOMPART "domestic partner"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#DAUADOPT "adopted daughter"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#SONINLAW "son in-law"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#NIENEPH "niece/nephew"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#UNCLE "uncle"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#GGRFTH "great grandfather"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#BROINLAW "brother-in-law"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#CHLDFOST "foster child"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#DAUC "daughter"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#SONC "son"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#STPCHLD "step child"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#DAUINLAW "daughter in-law"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#COUSN "cousin"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#SON "natural son"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#SPS "spouse"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#CHLDADOPT "adopted child"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#NCHILD "natural child"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#SIGOTHR "significant other"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#GGRMTH "great grandmother"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#MTH "Mother"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#MTHINLAW "mother-in-law"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#BRO "Brother"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#HUSB "husband"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#PRN "Parent"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#SIB "Sibling"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#NIECE "niece"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#FTH "Father"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#FTHINLAW "father-in-law"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#STPSON "stepson"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#SONFOST "foster son"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#GGRPRN "great grandparent"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#GRNDCHILD "grandchild"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#EXT "extended family member"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#SISINLAW "sister-in-law"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#WIFE "wife"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#DAU "natural daughter"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#GRPRN "Grandparent"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#CHILD "Child"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#GRNDDAU "granddaughter"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#GRFTH "Grandfather"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#PRNINLAW "parent in-law"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#ROOM "Roommate"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#CHLDINLAW "child in-law"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#SONADOPT "adopted son"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#STPDAU "stepdaughter"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#NEPHEW "nephew"
* http://terminology.hl7.org/CodeSystem/v3-RoleCode#SIS "Sister"
