ValueSet: EHDSIVaccine
Id: eHDSIVaccine
Title: "eHDSI Vaccine"
Description: "The Value Set is used to identify the patient's vaccinations in the Patient Summary"

* ^url = "http://terminology.ehdsi.eu/ValueSet/eHDSIVaccine"
* ^experimental = false
* ^name = "EHDSIVaccine"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.3.6.1.4.1.12559.11.10.1.3.1.42.28"

* http://snomed.info/sct#428601009 "Paratyphoid vaccine"
* http://snomed.info/sct#836383009 "Vibrio cholerae antigen-containing vaccine product"
* http://snomed.info/sct#836495005 "Human alphaherpesvirus 3 antigen-containing vaccine product"
* http://snomed.info/sct#836500008 "Haemophilus influenzae type b and Neisseria meningitidis serogroup C antigens only vaccine product"
* http://snomed.info/sct#871738001 "Live attenuated Mumps orthorubulavirus antigen only vaccine product"
* http://snomed.info/sct#871768005 "Influenza virus antigen only vaccine product in nasal dose form"
* http://snomed.info/sct#871839001 "Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Haemophilus influenzae type b antigens only vaccine product"
* http://snomed.info/sct#871889009 "Acellular Bordetella pertussis and Corynebacterium diphtheriae and Hepatitis B virus and inactivated whole Human poliovirus antigens only vaccine product"
* http://snomed.info/sct#1119349007 "SARS-CoV-2 mRNA vaccine"
* http://snomed.info/sct#1157024006 "Inactivated whole SARS-CoV-2 antigen vaccine"
* http://snomed.info/sct#601000221108 "Bordetella pertussis antigen-containing vaccine product"
* http://snomed.info/sct#29061000087103 "COVID-19 non-replicating viral vector vaccine"
* http://www.whocc.no/atc#J07AE51 "cholera, combinations with typhoid vaccine, inactivated, whole cell"
* http://www.whocc.no/atc#J07AH01 "meningococcus A, purified polysaccharides antigen"
* http://www.whocc.no/atc#J07AH06 "meningococcus B, outer membrane vesicle vaccine"
* http://www.whocc.no/atc#J07BB03 "influenza, live attenuated"
* http://www.whocc.no/atc#J07BC01 "hepatitis B, purified antigen"
* http://www.whocc.no/atc#J07BD "Measles vaccines"
* http://www.whocc.no/atc#J07BJ "Rubella vaccines"
* http://www.whocc.no/atc#J07BJ01 "rubella, live attenuated"
* http://www.whocc.no/atc#J07BX05 "respiratory syncytial virus vaccines"
* http://www.whocc.no/atc#J07CA01 "diphtheria-poliomyelitis-tetanus"
* http://www.whocc.no/atc#J07CA06 "diphtheria-haemophilus influenzae B-pertussis-poliomyelitis-tetanus"
* http://www.whocc.no/atc#J07XA01 "malaria vaccines"
* http://snomed.info/sct#836380007 "Haemophilus influenzae type b antigen-containing vaccine product"
* http://snomed.info/sct#836384003 "Bacillus anthracis antigen-containing vaccine product"
* http://snomed.info/sct#836393002 "Rabies lyssavirus antigen-containing vaccine product"
* http://snomed.info/sct#836402002 "Bacillus Calmette-Guerin antigen-containing vaccine product"
* http://snomed.info/sct#871875004 "Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae antigens only vaccine product"
* http://snomed.info/sct#1052328007 "Streptococcus pneumoniae Danish serotype 4, 6B, 9V, 14, 18C, 19F, and 23F capsular polysaccharide antigens conjugated only vaccine product"
* http://snomed.info/sct#971000221109 "Live attenuated Salmonella enterica subspecies enterica serovar Typhi antigen only vaccine product in oral dose form"
* http://snomed.info/sct#2221000221107 "Live attenuated Human alphaherpesvirus 3 only vaccine product"
* http://www.whocc.no/atc#J07AE02 "cholera, live attenuated"
* http://www.whocc.no/atc#J07AG51 "haemophilus influenzae B, combinations with toxoids"
* http://www.whocc.no/atc#J07AH07 "meningococcus C, purified polysaccharides antigen conjugated"
* http://www.whocc.no/atc#J07AH09 "meningococcus B, multicomponent vaccine"
* http://www.whocc.no/atc#J07AP10 "typhoid, combinations with paratyphi types"
* http://www.whocc.no/atc#J07BA "Encephalitis vaccines"
* http://www.whocc.no/atc#J07BA03 "encephalitis, Japanese, live attenuated"
* http://www.whocc.no/atc#J07BE "Mumps vaccines"
* http://www.whocc.no/atc#J07BL "Yellow fever vaccines"
* http://www.whocc.no/atc#J07BM01 "papillomavirus (human types 6, 11, 16, 18)"
* http://www.whocc.no/atc#J07BN05 "covid-19, virus-like particles"
* http://www.whocc.no/atc#J07BX "Other viral vaccines"
* http://www.whocc.no/atc#J07CA03 "diphtheria-rubella-tetanus"
* http://www.whocc.no/atc#J07CA07 "diphtheria-hepatitis B-tetanus"
* http://www.whocc.no/atc#J07CA09 "diphtheria-haemophilus influenzae B-pertussis-poliomyelitis-tetanus-hepatitis B"
* http://snomed.info/sct#836375003 "Hepatitis A virus antigen-containing vaccine product"
* http://snomed.info/sct#836378001 "Japanese encephalitis virus antigen-containing vaccine product"
* http://snomed.info/sct#871803007 "Hepatitis A and Hepatitis B virus antigens only vaccine product"
* http://snomed.info/sct#1801000221105 "Streptococcus pneumoniae capsular polysaccharide antigen conjugated only vaccine product"
* http://snomed.info/sct#871751006 "Hepatitis A virus antigen only vaccine product"
* http://snomed.info/sct#871739009 "Human poliovirus antigen only vaccine product"
* http://www.whocc.no/atc#J07AH05 "other meningococcal polyvalent purified polysaccharides antigen"
* http://www.whocc.no/atc#J07AH08 "meningococcus A,C,Y,W-135, tetravalent purified polysaccharides antigen conjugated"
* http://www.whocc.no/atc#J07AH10 "meningococcus A, purified polysaccharides antigen conjugated"
* http://www.whocc.no/atc#J07AP02 "typhoid, inactivated, whole cell"
* http://www.whocc.no/atc#J07AX "Other bacterial vaccines"
* http://www.whocc.no/atc#J07BD53 "measles, combinations with rubella, live attenuated"
* http://www.whocc.no/atc#J07BD54 "measles, combinations with mumps, rubella and varicella, live attenuated"
* http://www.whocc.no/atc#J07BF "Poliomyelitis vaccines"
* http://www.whocc.no/atc#J07BF01 "poliomyelitis oral, monovalent, live attenuated"
* http://www.whocc.no/atc#J07BF04 "poliomyelitis oral, bivalent, live attenuated"
* http://www.whocc.no/atc#J07BG "Rabies vaccines"
* http://www.whocc.no/atc#J07BH "Rota virus diarrhea vaccines"
* http://www.whocc.no/atc#J07BH01 "rota virus, live attenuated"
* http://www.whocc.no/atc#J07BM "Papillomavirus vaccines"
* http://www.whocc.no/atc#J07BN "Covid-19 vaccines"
* http://www.whocc.no/atc#J07BN03 "covid-19, inactivated virus"
* http://www.whocc.no/atc#J07CA05 "diphtheria-hepatitis B-pertussis-tetanus"
* http://www.whocc.no/atc#J07XA "Parasitic vaccines"
* http://snomed.info/sct#37146000 "Typhus vaccine"
* http://snomed.info/sct#775641005 "Clostridium tetani toxoid adsorbed and Corynebacterium diphtheriae toxoid antigens only vaccine product"
* http://snomed.info/sct#777725002 "Clostridium tetani toxoid antigen adsorbed only vaccine product"
* http://snomed.info/sct#836379009 "Human papillomavirus antigen-containing vaccine product"
* http://snomed.info/sct#836382004 "Measles morbillivirus antigen-containing vaccine product"
* http://snomed.info/sct#836390004 "Salmonella enterica subspecies enterica serovar Typhi antigen-containing vaccine product"
* http://snomed.info/sct#836398006 "Streptococcus pneumoniae antigen-containing vaccine product"
* http://snomed.info/sct#840563003 "Dengue virus antigen-containing vaccine product"
* http://snomed.info/sct#863911006 "Clostridium tetani antigen-containing vaccine product"
* http://snomed.info/sct#871759008 "Acellular Bordetella pertussis only vaccine product"
* http://snomed.info/sct#871878002 "Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Human poliovirus antigens only vaccine product"
* http://snomed.info/sct#1119254000 "Streptococcus pneumoniae Danish serotype 1, 3, 4, 5, 6A, 6B, 7F, 9V, 14, 18C, 19A, 19F, and 23F capsular polysaccharide antigens only vaccine product"
* http://snomed.info/sct#1001000221103 "Inactivated whole Vibrio cholerae antigen only vaccine product in oral dose form"
* http://snomed.info/sct#1011000221100 "Live attenuated Vibrio cholerae antigen only vaccine product in oral dose form"
* http://snomed.info/sct#871764007 "Haemophilus influenzae type b antigen only vaccine product"
* http://www.whocc.no/atc#J07AC01 "anthrax antigen"
* http://www.whocc.no/atc#J07AE01 "cholera, inactivated, whole cell"
* http://www.whocc.no/atc#J07AF "Diphtheria vaccines"
* http://www.whocc.no/atc#J07AG53 "haemophilus influenzae B, combinations with meningococcus C, conjugated"
* http://www.whocc.no/atc#J07AH "Meningococcal vaccines"
* http://www.whocc.no/atc#J07AJ01 "pertussis, inactivated, whole cell"
* http://www.whocc.no/atc#J07AL52 "pneumococcus purified polysaccharides antigen and haemophilus influenzae, conjugated"
* http://www.whocc.no/atc#J07AM51 "tetanus toxoid, combinations with diphtheria toxoid"
* http://www.whocc.no/atc#J07AP01 "typhoid, oral, live attenuated"
* http://www.whocc.no/atc#J07AP03 "typhoid, purified polysaccharide antigen"
* http://www.whocc.no/atc#J07BA01 "encephalitis, tick borne, inactivated, whole virus"
* http://www.whocc.no/atc#J07BA02 "encephalitis, Japanese, inactivated, whole virus"
* http://www.whocc.no/atc#J07BD51 "measles, combinations with mumps, live attenuated"
* http://www.whocc.no/atc#J07BK03 "zoster, purified antigen"
* http://www.whocc.no/atc#J07BN02 "covid-19, viral vector, non-replicating"
* http://www.whocc.no/atc#J07BN04 "covid-19, protein subunit"
* http://www.whocc.no/atc#J07CA "Bacterial and viral vaccines, combined"
* http://www.whocc.no/atc#J07CA02 "diphtheria-pertussis-poliomyelitis-tetanus"
* http://www.whocc.no/atc#J07CA10 "typhoid-hepatitis A"
* http://www.whocc.no/atc#J07CA11 "diphtheria-haemophilus influenzae B-pertussis-tetanus-hepatitis B"
* http://www.whocc.no/atc#J07CA12 "diphtheria-pertussis-poliomyelitis-tetanus-hepatitis B"
* http://snomed.info/sct#836368004 "Bacteria antigen-containing vaccine product"
* http://snomed.info/sct#836377006 "Influenza virus antigen-containing vaccine product"
* http://snomed.info/sct#836385002 "Yellow fever virus antigen-containing vaccine product"
* http://snomed.info/sct#836387005 "Rotavirus antigen-containing vaccine product"
* http://snomed.info/sct#836388000 "Rubella virus antigen-containing vaccine product"
* http://snomed.info/sct#836397001 "Coxiella burnetii antigen-containing vaccine product"
* http://snomed.info/sct#836401009 "Neisseria meningitidis antigen-containing vaccine product"
* http://snomed.info/sct#871804001 "Hepatitis A virus and Salmonella enterica subspecies enterica serovar Typhi antigens only vaccine product"
* http://snomed.info/sct#871831003 "Measles morbillivirus and Mumps orthorubulavirus and Rubella virus antigens only vaccine product"
* http://snomed.info/sct#871837004 "Clostridium tetani and Corynebacterium diphtheriae and Human poliovirus antigens only vaccine product"
* http://snomed.info/sct#1119305005 "SARS-CoV-2 antigen vaccine"
* http://snomed.info/sct#1121000221106 "Live attenuated Yellow fever virus antigen only vaccine product"
* http://snomed.info/sct#1181000221105 "Influenza virus antigen only vaccine product"
* http://snomed.info/sct#1861000221106 "Bacillus Calmette-Guerin antigen only vaccine product"
* http://www.whocc.no/atc#J07AE "Cholera vaccines"
* http://www.whocc.no/atc#J07AG01 "haemophilus influenzae B, purified antigen conjugated"
* http://www.whocc.no/atc#J07AH02 "other meningococcal monovalent purified polysaccharides antigen"
* http://www.whocc.no/atc#J07AL "Pneumococcal vaccines"
* http://www.whocc.no/atc#J07AL01 "pneumococcus, purified polysaccharides antigen"
* http://www.whocc.no/atc#J07AM01 "tetanus toxoid"
* http://www.whocc.no/atc#J07AN "Tuberculosis vaccines"
* http://www.whocc.no/atc#J07AP "Typhoid vaccines"
* http://www.whocc.no/atc#J07AR01 "typhus exanthematicus, inactivated, whole cell"
* http://www.whocc.no/atc#J07AX01 "leptospira vaccines"
* http://www.whocc.no/atc#J07BC20 "combinations"
* http://www.whocc.no/atc#J07BD52 "measles, combinations with mumps and rubella, live attenuated"
* http://www.whocc.no/atc#J07BE01 "mumps, live attenuated"
* http://www.whocc.no/atc#J07BK02 "zoster, live attenuated"
* http://www.whocc.no/atc#J07BM02 "papillomavirus (human types 16, 18)"
* http://www.whocc.no/atc#J07BM03 "papillomavirus (human types 6, 11, 16, 18, 31, 33, 45, 52, 58)"
* http://www.whocc.no/atc#J07BX04 "dengue virus vaccines"
* http://www.whocc.no/atc#J07CA04 "haemophilus influenzae B and poliomyelitis"
* http://snomed.info/sct#409568008 "Pentavalent botulinum toxoid vaccine"
* http://snomed.info/sct#836381006 "Corynebacterium diphtheriae antigen-containing vaccine product"
* http://snomed.info/sct#871737006 "Mumps orthorubulavirus antigen only vaccine product"
* http://snomed.info/sct#871871008 "Neisseria meningitidis serogroup A and C only vaccine product"
* http://snomed.info/sct#871873006 "Neisseria meningitidis serogroup A, C, W135 and Y only vaccine product"
* http://snomed.info/sct#871908002 "Human alphaherpesvirus 3 and Measles morbillivirus and Mumps orthorubulavirus and Rubella virus antigens only vaccine product"
* http://snomed.info/sct#1051000221104 "Live attenuated Human poliovirus serotypes 1 and 3 antigens only vaccine product in oral dose form"
* http://snomed.info/sct#1131000221109 "Vaccine product containing only inactivated whole Rabies lyssavirus antigen"
* http://www.whocc.no/atc#J07AD "Brucellosis vaccines"
* http://www.whocc.no/atc#J07AH03 "meningococcus A,C, bivalent purified polysaccharides antigen"
* http://www.whocc.no/atc#J07AH04 "meningococcus A,C,Y,W-135, tetravalent purified polysaccharides antigen"
* http://www.whocc.no/atc#J07AJ52 "pertussis, purified antigen, combinations with toxoids"
* http://www.whocc.no/atc#J07AM "Tetanus vaccines"
* http://www.whocc.no/atc#J07AM52 "tetanus toxoid, combinations with tetanus immunoglobulin"
* http://www.whocc.no/atc#J07BB04 "influenza, virus like particles"
* http://www.whocc.no/atc#J07BC02 "hepatitis A, inactivated, whole virus"
* http://www.whocc.no/atc#J07BF03 "poliomyelitis, trivalent, inactivated, whole virus"
* http://www.whocc.no/atc#J07BK "Varicella zoster vaccines"
* http://www.whocc.no/atc#J07BK01 "varicella, live attenuated"
* http://www.whocc.no/atc#J07BX02 "ebola vaccines"
* http://snomed.info/sct#836389008 "Vaccinia virus antigen-containing vaccine product"
* http://snomed.info/sct#836403007 "Tick-borne encephalitis virus antigen-containing vaccine product"
* http://snomed.info/sct#836498007 "Mumps orthorubulavirus antigen-containing vaccine product"
* http://snomed.info/sct#871740006 "Inactivated whole Human poliovirus antigen only vaccine product"
* http://snomed.info/sct#871765008 "Measles morbillivirus antigen only vaccine product"
* http://snomed.info/sct#871806004 "Haemophilus influenzae type b and Hepatitis B virus antigens only vaccine product"
* http://snomed.info/sct#871866001 "Neisseria meningitidis serogroup C only vaccine product"
* http://snomed.info/sct#871895005 "Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Haemophilus influenzae type b and Hepatitis B virus and Human poliovirus antigens only vaccine product"
* http://snomed.info/sct#871921009 "Staphylococcus toxoid vaccine"
* http://snomed.info/sct#1162643001 "SARS-CoV-2 recombinant spike protein antigen vaccine"
* http://snomed.info/sct#1031000221108 "Human poliovirus antigen-containing vaccine product"
* http://snomed.info/sct#1101000221104 "Clostridium tetani toxoid antigen-containing vaccine product"
* http://snomed.info/sct#2171000221104 "Salmonella enterica subspecies enterica serovar Typhi capsular polysaccharide unconjugated antigen only vaccine product in parenteral dose form"
* http://snomed.info/sct#921000221108 "Neisseria meningitidis antigen only vaccine product"
* http://www.whocc.no/atc#J07AD01 "brucella antigen"
* http://www.whocc.no/atc#J07AF01 "diphtheria toxoid"
* http://www.whocc.no/atc#J07AG52 "haemophilus influenzae B, combinations with pertussis and toxoids"
* http://www.whocc.no/atc#J07AJ02 "pertussis, purified antigen"
* http://www.whocc.no/atc#J07AJ51 "pertussis, inactivated, whole cell, combinations with toxoids"
* http://www.whocc.no/atc#J07AK01 "plague, inactivated, whole cell"
* http://www.whocc.no/atc#J07AR "Typhus (exanthematicus) vaccines"
* http://www.whocc.no/atc#J07BB01 "influenza, inactivated, whole virus"
* http://www.whocc.no/atc#J07BF02 "poliomyelitis oral, trivalent, live attenuated"
* http://www.whocc.no/atc#J07BJ51 "rubella, combinations with mumps, live attenuated"
* http://www.whocc.no/atc#J07BN01 "covid-19, RNA-based vaccine"
* http://www.whocc.no/atc#J07BX01 "smallpox and monkeypox vaccines"
* http://www.whocc.no/atc#J07CA13 "diphtheria-haemophilus influenzae B-pertussis-tetanus-hepatitis B-meningococcus A + C"
* http://snomed.info/sct#836374004 "Hepatitis B virus antigen-containing vaccine product"
* http://snomed.info/sct#840549009 "Yersinia pestis antigen-containing vaccine product"
* http://snomed.info/sct#840599008 "Borrelia burgdorferi antigen-containing vaccine product"
* http://snomed.info/sct#871772009 "Influenza A virus subtype H1N1 antigen only vaccine product"
* http://snomed.info/sct#871887006 "Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Haemophilus influenzae type b and Human poliovirus antigens only vaccine product"
* http://snomed.info/sct#871918007 "Rickettsia antigen-containing vaccine product"
* http://snomed.info/sct#871726005 "Rabies lyssavirus antigen only vaccine product"
* http://www.whocc.no/atc#J07AC "Anthrax vaccines"
* http://www.whocc.no/atc#J07AG "Haemophilus influenzae B vaccines"
* http://www.whocc.no/atc#J07AG54 "haemophilus influenza B, combinations with meningococcus C,Y, conjugated"
* http://www.whocc.no/atc#J07AJ "Pertussis vaccines"
* http://www.whocc.no/atc#J07AK "Plague vaccines"
* http://www.whocc.no/atc#J07AL02 "pneumococcus, purified polysaccharides antigen conjugated"
* http://www.whocc.no/atc#J07AN01 "tuberculosis, live attenuated"
* http://www.whocc.no/atc#J07BB "Influenza vaccines"
* http://www.whocc.no/atc#J07BB02 "influenza, inactivated, split virus or surface antigen"
* http://www.whocc.no/atc#J07BC "Hepatitis vaccines"
* http://www.whocc.no/atc#J07BD01 "measles, live attenuated"
* http://www.whocc.no/atc#J07BG01 "rabies, inactivated, whole virus"
* http://www.whocc.no/atc#J07BH02 "rota virus, pentavalent, live, reassorted"
* http://www.whocc.no/atc#J07BL01 "yellow fever, live attenuated"
* http://www.whocc.no/atc#J07BX06 "enterovirus 71 vaccines"
* http://www.whocc.no/atc#J07CA08 "haemophilus influenzae B and hepatitis B"
* http://snomed.info/sct#1081000221109 "Live attenuated Rotavirus antigen only vaccine product"
* http://snomed.info/sct#871826000 "Clostridium tetani and Corynebacterium diphtheriae antigens only vaccine product"
* http://snomed.info/sct#871876003 "Acellular Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae antigens only vaccine product"
* http://snomed.info/sct#871742003 "Clostridium tetani antigen only vaccine product"
* http://snomed.info/sct#1981000221108 "Neisseria meningitidis serogroup B antigen only vaccine product"
* http://snomed.info/sct#28531000087107 "COVID-19 vaccine"
* http://snomed.info/sct#981000221107 "Streptococcus pneumoniae antigen only vaccine product"
* http://snomed.info/sct#836369007 "Virus antigen-containing vaccine product"
* http://snomed.info/sct#774618008 "Whole cell Bordetella pertussis and Clostridium tetani toxoid adsorbed and Corynebacterium diphtheriae toxoid antigens only vaccine product"
