
id: hl7.eu.terminology.ehdsi
canonical: http://hl7europe.org/fhir/terminology/ehdsi
name: EHDSI
title: eHDSI Terminologies
description: Implementation Guide...
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 Europe
  url: http://hl7europe.org
  # email: test@example.org

menu:
  Home: index.html
  Artifacts:
    Profiles: artifacts.html

parameters:
  # translation-supplements: input/translations  
  # i18n-default-lang: en
  # i18n-lang: 
  #   - pt
  #   - nl
  #   - fr
  #   - es
  #   - ee
  no-narrative:
    - ValueSet/*
  special-url:
    - http://hl7.org/fhir/uv/ips/ValueSet/results-blood-group-uv-ips
    - http://hl7.org/fhir/uv/ips/ValueSet/results-presence-absence-uv-ips
    - http://hl7.org/fhir/uv/ips/ValueSet/results-microorganism-uv-ips
    - http://hl7.org/fhir/uv/ips/ValueSet/results-coded-values-laboratory-uv-ips
    - http://www.whocc.no/atc
  special-url-base:
    - http://terminology.ehdsi.eu/ValueSet

